// Plain JS export so we can keep everything in JavaScript-only (no CSS modules tooling changes)
// Maps semantic names to global CSS class names from styles/globals.css
export default {
    appShell: 'appShell',
    shell: 'shell',
    sidebar: 'sidebar',
    brand: 'brand',
    logo: 'logo',
    brandTitle: 'brandTitle',
    nav: 'nav',
    navSection: 'navSection',
    navLink: 'navLink',
    navLinkActive: 'navLinkActive',
    main: 'main',
    topbar: 'topbar',
    topbarInner: 'topbarInner',
    mobileTop: 'mobileTop',
    topLeft: 'topLeft',
    pageTitle: 'pageTitle',
    subtitle: 'subtitle',
    actions: 'actions',
    chip: 'chip',
    button: 'button',
    content: 'content',
    divider: 'divider',
    drawerOverlay: 'drawerOverlay',
    drawerOverlayOpen: 'drawerOverlayOpen',
    drawer: 'drawer',
    bottomNav: 'bottomNav',
};
